### ISSUE TITLE
Italics tags <i></i>

### ISSUE THREAD

**Issue by samtazzyman** [moj-analytical-services/pq-tool#100]
The text for answers displayed on screen contains italics tags <i> </i> rather than italicising the surrounded text.

**Comment by andrewPoulton** [comment]
Addressed by PR102 (hopefully)

**Comment by EdwardAndress** [comment]
@samtazzyman has this now been addressed?

**Comment by samtazzyman** [comment]
Yup - check by searching for "thebigword"
