### ISSUE TITLE
Quick tour fails if you haven't yet entered a search term/haven't entered one which returns results

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/pq-tool#105]
Not sure if we care but was testing and ran into this issue!

**Comment by RossKen** [comment]
@RobinL 
Yea the tour is pretty fragile at the moment, you need to follow the instructions exactly for it not to break. Am having a think on how to make it more stable

**Comment by EdwardAndress** [comment]
Fixed as of https://github.com/moj-analytical-services/pq-tool/pull/144 (well, as soon as the build passes anyway)
